module.exports = [
    {
        title: 'hand sanitizer', 
        upc: 681131247634,
        quantity: 1,
        quantityType: 'bottle(s)',
        price: 20,
        location: 'desk',
        caseQty: 1,
        date: '2021-04-28',
        shelfLife: 2,
        expiration_date: "2021-07-30",
                
    },        
    {
        title: 'can of coke', 
        upc: 111,
        quantity: 0,
        quantityType: 'can(s)',
        price: 1,
        location: 'fridge',
        caseQty: 1,
        date: '2021-04-28',
        shelfLife: 2,
        expiration_date: "2021-07-30",
                    
    },        
    {
        title: 'case of coke', 
        upc: 123,
        quantity: 1,
        quantityType: 'cases',
        price: 8,
        location: 'fridge',
        caseQty: 24,
        date: '2021-04-28',
        shelfLife: 2,
        expiration_date: "2021-07-30",           
    },        
    {
        title: 'brick', 
        upc: 810011753013,
        quantity: 2,
        quantityType: 'brick(s)',
        price: 5,
        location: 'desk',
        caseQty: 1,
        date: '2021-04-28',
        shelfLife: 2,
        expiration_date: "2021-07-30",           
    },        
    {
        title: 'Honey', 
        upc: 681131247669,
        quantity: 7,
        quantityType: 'bottle(s)',
        price: 2,
        location: 'desk',
        caseQty: 5,
        date: '2021-04-28',
        shelfLife: 2,
        expiration_date: "2021-07-30",           
    },        
];